{
 "title": "Spams-Remover",
 "time": { "from": "now-6d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Ratio by country",
   "type": "piechart",
   "gridPos": { "h": 16, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  1 AS \"time\",\n  COUNT(*),\n  COALESCE(NULLIF(country,''),'Unknown') AS \"Country\"\nFROM spams\nWHERE\n  $__timeFilter(time)\nGROUP BY 3\nORDER BY 1, 3"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  1 AS \"time\",\n  COUNT(*) as \"Total\"\nFROM spams\nWHERE\n  $__timeFilter(time)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Hourly frequency",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 10, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,1h,0),\n  count(*) as \"Spam\"\nFROM spams\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Total by day of the week",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 6, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT 1 AS \"time\",\r\n       EXTRACT(dow from time) AS dow,\r\n       COUNT(*) AS total\r\nFROM spams\r\nWHERE\r\n  $__timeFilter(time)\r\nGROUP BY 1, 2\r\nORDER BY 1, 2;"
    }
   ]
  },
  {
   "title": "Map of origns",
   "type": "geomap",
   "gridPos": { "h": 11, "w": 18, "x": 4, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT time_bucket('1h', time) AS time,\r\n       location_latitude AS latitude,\r\n       location_longitude AS longitude,\r\n       COALESCE(NULLIF(city,''),'Unknown') AS city,\r\n       COALESCE(NULLIF(region,''),'Unknown') AS region,\r\n       COALESCE(NULLIF(organization,''),'Unknown') AS organization\r\nFROM spams\r\nWHERE $__timeFilter(time) AND\r\n  \t  location_latitude IS NOT NULL AND\r\n  \t  location_longitude IS NOT NULL\r\nGROUP BY time,\r\n         location_latitude,\r\n         location_longitude,\r\n         city,\r\n         region,\r\n         organization\r\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Ratio of invalid addresses",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  1 AS \"time\",\r\n  COUNT(*) as \"valid\"\r\nFROM spams\r\nWHERE\r\n  $__timeFilter(time) AND \r\n  is_email_valid IS NOT FALSE\r\nORDER BY 1, 2"
    },
    {
     "rawSql": "SELECT\n  1 AS \"time\",\n  COUNT(*) as \"invalid\"\nFROM spams\nWHERE\n  $__timeFilter(time) AND \n  is_email_valid IS NOT TRUE\nORDER BY 1, 2\n"
    }
   ]
  }
 ]
}